/**
 * Introspects real embedded fonts from a test PDF and checks that
 * getFontInfo returns the correct family / bold / italic state.
 *
 * Requires public/test-fonts.pdf (generated by scripts/generateTestPdf.ts).
 */
import { describe, it, expect, beforeAll } from "vitest";
import fs from "fs";
import path from "path";
import * as pdfjsLib from "pdfjs-dist/legacy/build/pdf.mjs";
import { getFontInfo } from "../../lib/pdf/fontIntrospect";

const PDF_PATH = path.join(__dirname, "../../../public/test-fonts.pdf");

function normalize(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, "");
}

describe("fontIntrospect.getFontInfo", () => {
  let doc: any;

  beforeAll(async () => {
    if (!fs.existsSync(PDF_PATH)) {
      console.warn(`[fontIntrospect.test] ${PDF_PATH} missing – skipping`);
      return;
    }
    const data = new Uint8Array(fs.readFileSync(PDF_PATH));
    doc = await pdfjsLib.getDocument({
      data,
      standardFontDataUrl: path.join(__dirname, "../../../node_modules/pdfjs-dist/standard_fonts/"),
    }).promise;
  });

  it("returns a usable descriptor for every embedded font", async () => {
    if (!doc) return; // skipped
    let tested = 0;
    let matched = 0;
    const failures: string[] = [];

    for (let p = 1; p <= doc.numPages; p++) {
      const page = await doc.getPage(p);
      const content = await page.getTextContent();
      for (const item of content.items as any[]) {
        const line = item.str as string;
        // Test PDF encodes: "<Family> - Bold <bool> - Italic <bool> - The quick brown fox"
        const m = line.match(/^(.*?) - Bold (true|false) - Italic (true|false) - /);
        if (!m || !item.fontName) continue;

        const [, expectedFamily, expectedBold, expectedItalic] = m;
        const info = await getFontInfo(page as any, item.fontName);
        tested++;

        const familyOk = normalize(info.family).includes(normalize(expectedFamily).slice(0, 6)) ||
                          normalize(expectedFamily).includes(normalize(info.family).slice(0, 6));
        const boldOk = info.isBold === (expectedBold === "true");
        const italicOk = info.isItalic === (expectedItalic === "true");

        if (familyOk && boldOk && italicOk) {
          matched++;
        } else {
          failures.push(
            `[p${p}] expected "${expectedFamily}" bold=${expectedBold} italic=${expectedItalic}; got "${info.family}" bold=${info.isBold} italic=${info.isItalic} (source=${info.source})`,
          );
        }
      }
    }

    if (failures.length) console.warn("Introspect mismatches:\n" + failures.slice(0, 20).join("\n"));
    // We insist on ≥ 90 % match – embedded-font parsing plus name fallback
    // should handle nearly everything the generator produces.
    if (tested > 0) {
      expect(matched / tested).toBeGreaterThanOrEqual(0.9);
    }
  });

  it("caches results per font name", async () => {
    if (!doc) return;
    const page = await doc.getPage(1);
    const content = await page.getTextContent();
    const first = (content.items as any[]).find((it) => it.fontName);
    if (!first) return;
    const a = await getFontInfo(page as any, first.fontName);
    const b = await getFontInfo(page as any, first.fontName);
    expect(a).toBe(b);
  });
});
